### ISSUE TITLE
Why you do not use the pre_weight in your code, which is used in your paper

### ISSUE THREAD

**Issue by junleiz** [kanchen-usc/QRC-Net#4]
Hello, the pred_weight is multiplied with the gradients of top k proposals in your paper:
![image](https://user-images.githubusercontent.com/26025961/57373854-043ec380-71cc-11e9-886a-81dc882d1e58.png)
But in your code, you never use it. Is this code different from your paper?

**Comment by kanchen-usc** [comment]
please check the line 173 of model.py
